// This test looks for a function-like macro with the right name to exist. For
// now the test doesn't require any specific code to be generated by the macro,
// so returning an empty TokenStream should be sufficient.
//
// Resources:
//
//   - Parsing in Syn:
//     https://docs.rs/syn/1.0/syn/parse/index.html
//
//   - An example of a function-like procedural macro implemented using Syn:
//     https://github.com/dtolnay/syn/tree/master/examples/lazy-static

use macro_rules2::macro_rules2;

macro_rules2! {
    test_macro {
        ($x:ident) => {
            println!("from test macro: {}", stringify!($x));
        },
    }
}

fn main() {
    test_macro!(hello);
}
